######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 14 16:34:43 2012
######################################################################

MONO_INSTALL = ../../mono_mono/install_64

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += $${MONO_INSTALL}/include/mono-2.0

LIBS += -L$${MONO_INSTALL}/lib -lmono-2.0

# Input
SOURCES += main.cpp
