######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 14 16:34:43 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
